### ISSUE TITLE
python path

### ISSUE THREAD

**Issue by T-Britton** [JeffersonLab/build_scripts#113]
All MC orders that contain random triggers fail when tested by the robot.  But succeed when I test them. They fail because the following needs to be added to the python path by default:

${HALLD_RECON_HOME}/${BMS_OSNAME}/python2

**Comment by markito3** [comment]
I looked. This is already in there. @T-Britton and I should sit down and look at this.

**Comment by T-Britton** [comment]
we sat down and found out that the cron job was not using the right python version.  @markito3 will look into adding this to build_scripts.  For now adding the apps directory to PATH fixes things
