### ISSUE TITLE
Building on AlmaLinux 9

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/build_scripts#256]
I started trying to build the GlueX software stack (latest version.xml) on a local AlmaLinux 9 machine, and thought I'd leave a few notes here, which could guide future developments.  I'll update this whenever I make more progress.

Note that one of the differences between RHEL8 and 9 is that 9 doesn't seem to have the python2 interpreter at all, so we can't rely on any workarounds.

* ~~Perhaps we are at the point where we can consider making cernlib/Geant3 an optionally built component~~ this was agreed to in the Aug. 14 GlueX Software meeting
* I ran into some compiler errors building Geant4.  Maybe we should move to a newer version as was being discussed? (note that 10.06.p01 compiles fine) - was agreed in principle
* ~~the build_scripts makefile for CCDB/HDDS doesn't support scons-3 (or at least the same scons switching logic as other packages)~~
* ~~a few SBMSes are not python3-compliant (CCDB, HDDS, ....)~~
* ~~in halld_recon, rpc/rpc.h doesn't exist anymore.  used gssrpc/rpc.h - but general suggestion is to use libtirpc-devel ?~~ - this seems to work out of the box
* AlmaLinux9 only has a newer version of QT, so hdgeant4 should not build with QT enabled until it is updated

**Comment by sdobbs** [comment]
strange problem building Diracxx

diracxx
-- Found Python3: /usr/bin/python3.9 (found version "3.9.16") found components: Interpreter Development Development.Module Development.Embed
-- Found PythonLibs: /usr/lib64/libpython3.9.so (found suitable version "3.9.16", minimum required is "3.6")
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: python3) (found suitable version "1.75.0",
  minimum required is "1.53")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBoost.cmake:2344 (find_package_handle_standard_args)
  src/CMakeLists.txt:6 (find_package)

**Comment by sdobbs** [comment]
It's not ready to be merged, but I'll keep the branch `sdobbs_almalinux9` up to date with my changes as I address some of these issues.

**Comment by sdobbs** [comment]
fwiw, ROOT 6.26 requires C++14
ROOT 6.24 seems to compile okay, except for the built-in xrootd, so we need to install xrootd-devel (and maybe xrootd-client-devel).  At least on my cluster, I get these from the OSG repositories - not sure about mainline installs.

**Comment by sdobbs** [comment]
The below version set seems to work for most/all packages except CCDB and the simulation packages

<pre>
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="https://halldweb.jlab.org/halld_versions/version7.xsl"?>
<gversions file="version_5.11.0.xml" date="2023-06-14">
<description>Update to halld_recon, halld_sim, hd_utilities</description>
<package name="amptools" version="0.14.5"/>
<package name="ccdb" version="1.06.09"/>
<package name="diracxx" version="2.0.2"/>
<package name="evio" version="4.4.6"/>
<package name="evtgen" version="01.07.00"/>
<package name="geant4" version="10.06.p01"/>
<package name="gluex_MCwrapper" version="v2.7.0"/>
<package name="gluex_root_analysis" version="1.24.0" dirtag="hdr441"/>
<package name="halld_recon" version="4.41.0"/>
<package name="halld_sim" version="4.45.0"/>
<package name="hdds" version="4.15.0"/>
<package name="hdgeant4" version="2.35.0" dirtag="hdr441"/>
<package name="hd_utilities" version="1.45"/>
<package name="hepmc" version="2.06.10"/>
<package name="jana" version="0.8.2" dirtag="ccdb169"/>
<package name="lapack" version="3.9.0"/>
<package name="photos" version="3.61"/>
<package name="rcdb" version="0.07.01"/>
<package name="root" version="6.26.10"/>
<package name="sqlitecpp" version="3.1.1"/>
<package name="sqlite" version="3.36.0" year="2021"/>
<package name="xerces-c" version="3.2.3"/>
</gversions>
</pre>

**Comment by aaust** [comment]
AlmaLinux9 is fully supported since build_scripts version [2.39](https://github.com/JeffersonLab/build_scripts/releases/tag/2.39)
