### ISSUE TITLE
Translate vsdb crawler into Python3

### ISSUE THREAD

**Issue by aaust** [JeffersonLab/build_scripts#270]
The script is currently running on a RHEL8 node which will be retired soon. Python2 is no longer available on RHEL9.
Most changes are trivial, but this line gives me a headache:

https://github.com/JeffersonLab/build_scripts/blob/e4b313a368c23f018ee18c365839799476cef1b1/vsdb/BScrawler.py#L102

**Comment by aaust** [comment]
`stdout,stderr = p.communicate(b'/group/halld/Software/build_scripts/vsdb/tables.sql')`

This line runs through, but produces the following error:

`ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '/group/halld/Software/build_scripts/vsdb/tables.sql' at line 1`

**Comment by aaust** [comment]
I made a branch with the trivial changes:
https://github.com/JeffersonLab/build_scripts/tree/vsdb_py3
It runs, but produces the error mentioned above.

**Comment by T-Britton** [comment]
should be fixed up in https://github.com/JeffersonLab/build_scripts/pull/271
